services:
  app:
    image: "liemartt/weather-app"
    ports:
      - "8082:8080"
    depends_on:
      - db
    environment:
      API_KEY: ${API_KEY}
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: weather-app
    ports:
      - "5432:5432"