services:
  app:
    build: .
    ports:
      - "8082:8080"
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: weather-app
    ports:
      - "5432:5432"